# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: SCHH Commons # the main title

tagline: Clear answers and helpful resources, powered by AI. # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  SCHH Commons is a community-sponsored resource hub for Sun City Hilton Head residents and prospective residents. Explore events, maps, chatbots, and curated knowledge to make life in SCHH easier to navigate.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://schh-commons.org" # the base hostname & protocol for your site

# Landing Page Configuration
landing_page:
  hero:
    title: "Welcome to SCHH Commons"
    subtitle: "Your community resource hub for Sun City Hilton Head"
    description: "Discover events, explore interactive maps, listen to community podcasts, and access helpful resources designed specifically for SCHH residents and prospective residents."
    cta:
      text: "Explore Resources"
      url: "/articles/"
  navigation:
    - title: "Articles"
      url: "/articles/"
      icon: "fas fa-newspaper"
      description: "Community articles and helpful resources for SCHH residents and prospective residents"
    - title: "Maps"
      url: "/maps/"
      icon: "fas fa-map-marked-alt"
      description: "Interactive maps and location guides to help you navigate Sun City Hilton Head"
    - title: "Podcasts"
      url: "/podcasts/"
      icon: "fas fa-podcast"
      description: "Community podcasts and audio content featuring local voices and topics"

github:
  username: rsnyder # change to your GitHub username
  owner_name: schh-commons
  repository_name: schh-commons.github.io
  source:
    branch: main

twitter:
  username: rdsnyderjr # change to your Twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Ron Snyder
  email: admin@schh-commons.org # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/rdsnyderjr # change to your Twitter homepage
    - https://github.com/rsnyder # change to your GitHub homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/logo.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

# paginate: 10

# The base URL of your site
baseurl: ""

# Collection Configuration
collections:
  tabs:
    output: true
    sort_by: order
  articles:
    output: true
    sort_by: date
    title: "Articles"
    description: "Community articles and helpful resources"
    permalink: /articles/:name/
  maps:
    output: true
    sort_by: date
    title: "Maps"
    description: "Interactive maps and location guides"
    permalink: /maps/:name/
  podcasts:
    output: true
    sort_by: date
    title: "Podcasts"
    description: "Community podcasts and audio content"
    permalink: /podcasts/:name/

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: articles
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: ""
      type: maps
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: ""
      type: podcasts
    values:
      layout: podcast
      comments: true
      toc: true

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
